bin/xtitle: Print a diagnostic on internal errors
This will make it clear when the script is not working.
Note that $LINNO will be the line with the error, not the
line in the `trap`.

diff --git a/bin/xtitle b/bin/xtitle
--- a/bin/xtitle
+++ b/bin/xtitle
@@ -1,6 +1,12 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
 
+trap '
+    errcode=$?
+    echo 1>&2 "$0: INTERNAL ERROR $errcode at line $LINENO"
+    exit $errcode
+' ERR
+
 print_xt() {
     echo 'xt() { eval $($HOME/.local/bin/xtitle -e "$@"); }'
 }
